**1. Introduction to NumPy**

In [77]:
lst = [10, 200, 90, 0]

import numpy as np
arr = np.array(lst)

print(arr + 10)

[ 20 210 100  10]


In [78]:
lst = [22, 45, 78, 50]

import numpy as np
import sys
arr = np.array(lst)
print(arr.nbytes)
print(sys.getsizeof(lst))

32
104


**2. NumPy Object Creation**

*Array Creation*

In [79]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
print('----')
print(b)

[1 2 3 4]
----
[[1 2 3 4]
 [5 6 7 8]]


In [80]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4], [5,6,7,8]])

print('The shape of the array a is ', a.shape)
print('The shape of the array b is ', b.shape)

The shape of the array a is  (4,)
The shape of the array b is  (2, 4)


In [81]:
print('The shape of the array a is ', a.ndim)
print('The shape of the array b is ', b.ndim)

The shape of the array a is  1
The shape of the array b is  2


In [82]:
print('The shape of the array a is ', a.size)
print('The shape of the array b is ', b.size)

The shape of the array a is  4
The shape of the array b is  8


In [83]:
print('The shape of the array a is ', a.dtype)
print('The shape of the array b is ', b.dtype)

The shape of the array a is  int64
The shape of the array b is  int64


In [84]:
print('The shape of the array a is ', a.itemsize)
print('The shape of the array b is ', b.itemsize)

The shape of the array a is  8
The shape of the array b is  8


*Matrix Creation*

In [85]:
print(np.array([5,6,8,45,12,52]).reshape(2,3))

[[ 5  6  8]
 [45 12 52]]


In [86]:
print(np.matrix([[1,2], [3,4]]))

[[1 2]
 [3 4]]


In [87]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
print( np.zeros( (4,3) ) )

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [89]:
print(np.ones( (3,3), dtype = np.float64 ))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [90]:
print(np.arange(1,20,dtype='int32'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [91]:
print(np.arange(1,20,2,dtype='int8'))

[ 1  3  5  7  9 11 13 15 17 19]


PRACTICE EXERCISE

In [92]:
marks = np.array([20,30,40])
IDs = np.array([0,2,4])

print(marks)
print(IDs)

[20 30 40]
[0 2 4]


ANOTHER PRACTICE EXERCISE

In [93]:
arr1 = [25,56,12,85,34,75]
arr1 = np.array(arr1)
print(np.array(arr1))
shape = arr1.shape
print(shape)
print(np.random.rand(shape[0]))
arr1.astype('complex')

[25 56 12 85 34 75]
(6,)
[0.09040301 0.86636438 0.40269354 0.99300493 0.58391251 0.56559788]


array([25.+0.j, 56.+0.j, 12.+0.j, 85.+0.j, 34.+0.j, 75.+0.j])

**3. Indexing & Slicing**

*Indexing*

In [94]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Pull out second element of third row
print(a[2][1])
print('==========')
# Pull out first two rows and columns
print(a[:2,:2])
print('==========')
# Pull all elements of the third row
print(a[2,:])

#start:stop

8
[[1 2]
 [4 5]]
[7 8 9]


In [96]:
print(a[1,1:])

[5 6]


*Integer Array Indexing*

In [97]:
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]])
print('==========')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('==========')

print(a[[0,0],[1,1]])
print('==========')

print(np.array([a[0,1],a[0,1]]))


[1 4 5]
[1 4 5]
[2 2]
[2 2]


*Boolean indexing*

In [98]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])

# Boolean condition for values greater than 3
mask = a > 3
print(mask)

# Masking for the above boolean condition in the array
print(a[mask])


[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


PRACTICE EXERCISE 

In [99]:
arr_new = np.array([3,4.5,3+5j, 0])
np.isreal(arr_new)

array([ True,  True, False,  True])

In [100]:
np.iscomplex(arr_new)

array([False, False,  True, False])

**4. VECTORIZATION**

In [101]:
'''Vectoriztion is the ability of NumPy by which 
operations on entire arrays rather than on one single element'''

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[arr > 2])


[3 4 5 6 7]


Vectorized Operations:

In [102]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print('===================================')
a = np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [103]:
a.sum()

91

In [104]:
a.min()

1

In [105]:
a.max(axis=0)

array([16, 25, 36])

In [106]:
a.cumsum(axis=1)

array([[ 1,  5, 14],
       [16, 41, 77]])

In [107]:
a.mean()

15.166666666666666

In [108]:
np.median(a)

12.5

In [109]:
np.corrcoef(a)

array([[1.        , 0.99633201],
       [0.99633201, 1.        ]])

In [110]:
np.std(a)

12.212243401148248

*Array Comparison & Understanding Axes Notation*

In [111]:
coefficients = np.array([1,-4,4])
roots = np.roots(coefficients)
print(roots)

[2. 2.]


In [112]:
a = np.array([5,6,7,8])
b = np.array([5,6,7,8])
print(np.array_equal(a,b))

True


*Axes Notation*

In [113]:
a = np.array([[2,5,7],[4,25,30]])

# computes sum over columns
print(a.sum(axis=0))
print('==========')

# computes sum over rows
print(a.sum(axis=1))
print('==========')

# computes total sum
print(a.sum())

[ 6 30 37]
[14 59]
73


In [114]:
c = np.array([[40,35,20],[21,48,70]])
print(c)

[[40 35 20]
 [21 48 70]]


In [115]:
c.max()

70

In [116]:
c.min()

20

In [117]:
print(c.max()-c.min())

50


In [118]:
print(c[0][2])
print(c[1][2])
print(c[:,2])
#pulls all the elements in the 3rd column

20
70
[20 70]


**5. BROADCASTING**


In [119]:
np.arange(3)+4

array([4, 5, 6])

In [120]:
np.ones((3,3))+ np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [121]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

PRACTICE EXERCISE

In [122]:
random_arr = np.random.random((5,5))
random_arr

array([[0.72125572, 0.73172937, 0.47869437, 0.85060931, 0.17119805],
       [0.02965475, 0.51476605, 0.5640564 , 0.83964252, 0.00758639],
       [0.9314012 , 0.02362269, 0.92122944, 0.91943905, 0.32432659],
       [0.23624209, 0.08310095, 0.4268678 , 0.31730286, 0.55680476],
       [0.96575545, 0.84949516, 0.64695309, 0.21593257, 0.00307372]])

In [123]:
min_val = random_arr.min()
min_val

0.0030737157758142786

In [124]:
max_val = random_arr.max()
max_val

0.9657554543311052

In [125]:
z_norm = (random_arr-min_val)/(max_val-min_val)

In [126]:
print(z_norm)

[[0.74602226 0.75690192 0.49405804 0.88039023 0.17464166]
 [0.02761144 0.53152804 0.58272912 0.86899831 0.0046876 ]
 [0.96431401 0.02134556 0.95374794 0.95188815 0.33370621]
 [0.24220712 0.08312948 0.44022242 0.3264102  0.57519637]
 [1.         0.87923289 0.6688393  0.22111031 0.        ]]


**Mini Project: "Make Sense of Census"**


Step 1 : Read the Data!

In [127]:
data_file = '/content/makeSenseOfCensus.csv'

In [128]:
#Loading the data
import numpy as np
data = np.genfromtxt(data_file, delimiter=',',skip_header=1)

In [129]:
print("nData: \n\n", data)

nData: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [130]:
#Printing the data
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


Step 2 : Append the Data

In [131]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
np.concatenate((data, new_record), axis=0)


array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

Step 3 : Check if it's a young country or old country

In [132]:
age = data[:, 0]


In [133]:
max_age = age.max()
max_age

90.0

In [134]:
min_age = age.min()
min_age

17.0

In [135]:
age_mean = age.mean()
age_mean

38.051

In [136]:
age_std = age.std()
age_std

13.342803266180612

Step 4: Let's check the country's race distribution to identify the minorities

In [137]:
data[data[:,2]==0]

array([[34.,  4.,  0.,  1.,  0.,  0., 45.,  0.],
       [35., 10.,  0.,  0.,  0.,  0., 40.,  0.],
       [60.,  6.,  0.,  0.,  0.,  0., 10.,  0.],
       [51.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [25., 10.,  0.,  0.,  0.,  0., 20.,  0.],
       [20.,  9.,  0.,  1.,  0.,  0., 48.,  0.],
       [23., 10.,  0.,  0.,  0.,  0., 25.,  0.],
       [29.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [27., 12.,  0.,  1.,  0.,  0., 40.,  0.],
       [31., 12.,  0.,  0.,  0.,  0., 40.,  0.]])

In [138]:
race_0= data[data[:, 2]==0]
race_1= data[data[:,2]==1]
race_2= data[data[:,2]==2]
race_3= data[data[:,2]==3]
race_4= data[data[:,2]==4]


In [139]:
len_0 = len(race_0)
print("Length of Race_0 is :",len_0)
print("Length of Race_1 is :",len(race_1))
print("Length of Race_2 is :",len(race_2))
print("Length of Race_3 is :",len(race_3))
print("Length of Race_4 is :",len(race_4))
print("Race_3 has the minimum number \
of citizens which is 6")

Length of Race_0 is : 10
Length of Race_1 is : 27
Length of Race_2 is : 110
Length of Race_3 is : 6
Length of Race_4 is : 847
Race_3 has the minimum number of citizens which is 6


In [140]:
minority_race = 3


Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place.

In [141]:
senior_citizens = age[age>60]
senior_citizens

array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

In [142]:
working_hours = data[:,6]
working_hours_sc = np.extract(age>60,working_hours)

working_hours_sum = working_hours_sc.sum()
working_hours_sum

1917.0

In [143]:
senior_citizens_len = len(senior_citizens)
senior_citizens_len


61

In [144]:
avg_working_hours = (working_hours_sum/senior_citizens_len)
print(avg_working_hours)
if avg_working_hours <25:
  print('govt policy is followed')
else :
  print('govt policy is not followed')


31.42622950819672
govt policy is not followed


Step 6: Let's check that higher educated people have better pay in general.

In [145]:
education = data[:,1]
high_ed = education[education>10]
low_ed = education[education<=10]
high_ed

array([13., 13., 13., 14., 14., 13., 13., 13., 12., 11., 14., 16., 13.,
       12., 13., 12., 13., 13., 13., 14., 11., 11., 15., 13., 11., 13.,
       16., 13., 13., 12., 13., 14., 16., 11., 13., 16., 12., 14., 13.,
       14., 13., 15., 11., 13., 13., 13., 13., 12., 12., 13., 12., 14.,
       11., 11., 13., 13., 13., 14., 14., 12., 14., 11., 13., 13., 13.,
       13., 13., 14., 16., 13., 13., 14., 14., 14., 13., 13., 13., 12.,
       13., 13., 11., 15., 13., 14., 13., 12., 12., 15., 13., 11., 13.,
       13., 14., 14., 13., 12., 13., 14., 15., 13., 13., 13., 13., 13.,
       14., 13., 12., 12., 12., 13., 14., 13., 14., 11., 13., 11., 14.,
       12., 11., 13., 11., 12., 13., 13., 13., 13., 11., 14., 13., 13.,
       12., 13., 11., 14., 13., 12., 13., 13., 13., 13., 11., 14., 16.,
       13., 14., 14., 13., 12., 14., 13., 12., 11., 12., 13., 13., 14.,
       13., 11., 13., 12., 13., 13., 13., 12., 13., 13., 13., 11., 11.,
       11., 13., 13., 13., 14., 12., 15., 11., 13., 16., 11., 13

In [146]:
income = data[:,7]
pay_high = np.extract(education > 10,income)
print('avg pay for education greater then 10 :',round(pay_high.mean(),2))
pay_low = np.extract(education <= 10,income)
print('avg pay for education less then or equal 10 :',round(pay_low.mean(),2))

avg pay for education greater then 10 : 0.43
avg pay for education less then or equal 10 : 0.14


**PROJECTPROJECT**

In [147]:
project_data = np.genfromtxt("/content/KAG_Conversion_Data.csv",delimiter=',',skip_header=1)

In [157]:
project_data_str = np.genfromtxt("/content/KAG_Conversion_Data.csv",delimiter=',',skip_header=1,dtype='str')

In [148]:
project_data

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])

In [149]:
print(np.unique(project_data[:,1],return_counts=True))

(array([ 916.,  936., 1178.]), array([ 54, 464, 625]))


In [150]:
campaign_916 = project_data[project_data[:,1]==916]
campaign_936 = project_data[project_data[:,1]==936]
campaign_1178 = project_data[project_data[:,1]==1178]

In [151]:
print('Number of times 916 campaign ran:', len(campaign_916))
print('Number of times 936 campaign ran:', len(campaign_936))
print('Number of times 1178 campaign ran:', len(campaign_1178))

Number of times 916 campaign ran: 54
Number of times 936 campaign ran: 464
Number of times 1178 campaign ran: 625


In [160]:
np.unique(project_data_str[:,3])

array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [153]:
amount = project_data[:,8]
print('The average amount spent on ads is', amount.mean())
print('The minimum amount spent on ads is', amount.min())
print('The maximum amount spent on ads is', amount.max())


The average amount spent on ads is 51.36065613141295
The minimum amount spent on ads is 0.0
The maximum amount spent on ads is 639.9499981


In [161]:
ad_id=project_data[:,0]

In [163]:
clicks = project_data[:,7]
print(clicks.max())
click_ad_id = ad_id[clicks==421.0]
print(click_ad_id)

421.0
[1121814.]
the ad with the most clicks did not have the most spent


In [174]:
got_product = project_data[:,10]
ppl_got_product = got_product[clicks==421.0]
print('The number of ppl that bought the product is', ppl_got_product)
print('The maximum number of purchases in this dataset is',got_product.max())
print('''the number of purchases for the most number of clicks \
is not the same as max number of purchases in dataset''')

The number of ppl that bought the product is [13.]
The maximum number of purchases in this dataset is 21.0
the number of purchase for the most number of clicks is not the same as max number of purchases in dataset


In [177]:
data = project_data_str[clicks==421.0]
data

array([['1121814', '1178', '144659', '30-34', 'F', '27', '2223278',
        '421', '612.3000032', '38', '13']], dtype='<U11')